package: facekitapi
generate:
  gin-server: true
  models: true
  embedded-spec: true
output-options:
  # to make sure that all types are generated
  skip-prune: true
output: gen/facekit/facekitapi.gen.go
import-mapping:
  ./common.yaml: github.com/I0Dzela/pisp-api/gen/common